export type LessonVariant = { label: string; gates: string; damping?: number };
export type Lesson = { id: string; title: string; n: number; question: string; choices: string[]; answer: number; explanation: string; variants: LessonVariant[] };
export const LESSONS: Lesson[] = [
  { id: "superposition", title: "Superposition", n: 1,
    question: "Start at |0⟩ and apply H. What will repeated Z measurements show?",
    choices: ["Always 0", "About half 0 and half 1", "Always 1"], answer: 1,
    explanation: "H prepares (|0⟩ + |1⟩)/√2. Each Z measurement gives one bit. The calculated probabilities are 50/50; a finite sample usually differs slightly.",
    variants: [{ label: "H", gates: "h q[0];" }] },
  { id: "phase", title: "Relative phase", n: 1,
    question: "Compare H with H then Z. Does Z change the Z-measurement probabilities?",
    choices: ["Yes, it forces 1", "No, but the relative phase changes"], answer: 1,
    explanation: "Z changes |+⟩ into |−⟩. Both give 50/50 in Z. Their X expectations are +1 and −1: a different measurement basis reveals the phase. Similar Z counts do not imply identical states.",
    variants: [{ label: "H: |+⟩", gates: "h q[0];" }, { label: "H then Z: |−⟩", gates: "h q[0]; z q[0];" }] },
  { id: "interference", title: "Interference", n: 1,
    question: "Add a final H to each previous circuit. Which outcomes appear?",
    choices: ["Both remain 50/50", "H H gives 0; H Z H gives 1"], answer: 1,
    explanation: "The final H turns relative phase into a measurable difference. Amplitudes add for one outcome and cancel for the other. H H returns |0⟩; H Z H produces |1⟩.",
    variants: [{ label: "H H", gates: "h q[0]; h q[0];" }, { label: "H Z H", gates: "h q[0]; z q[0]; h q[0];" }] },
  { id: "entanglement", title: "Entanglement", n: 2,
    question: "Apply H to q0, then CX from q0 to q1. Which bitstrings can appear?",
    choices: ["All four equally", "Only 00 and 11", "Only 01 and 10"], answer: 1,
    explanation: "The circuit prepares the Bell state (|00⟩ + |11⟩)/√2. Each qubit is individually random, but the pair agrees. Z correlations alone do not prove entanglement: a classical mixture can have the same counts. The known preparation and phase-sensitive tests distinguish them.",
    variants: [{ label: "Bell pair", gates: "h q[0]; cx q[0], q[1];" }] },
  { id: "measurement", title: "Measurement", n: 1,
    question: "Insert a Z measurement between two H gates. Does the circuit still always end in 0?",
    choices: ["Yes, H H cancels regardless", "No, the intermediate measurement removes interference"], answer: 1,
    explanation: "Without measurement, H H gives 0. Measuring in between leaves |0⟩ or |1⟩; the last H gives equal Z probabilities in either branch. QC-1 replays the intermediate measurement for each sampled shot.",
    variants: [{ label: "H H", gates: "h q[0]; h q[0];" }, { label: "H, measure, H", gates: "h q[0]; c[0] = measure q[0]; h q[0];" }] },
  { id: "noise", title: "Noise", n: 1,
    question: "Prepare |1⟩ with X, then apply 30% amplitude damping. How does P(1) change?",
    choices: ["It stays 100%", "It falls to 70%", "It falls to 50%"], answer: 1,
    explanation: "Amplitude damping models relaxation from |1⟩ to |0⟩. Here it acts once, after X, so P(1)=0.7 and P(0)=0.3. This is a mixed state, not a coherent superposition with those probabilities. Sampling adds fluctuations around the density-matrix prediction.",
    variants: [{ label: "Ideal X", gates: "x q[0];" }, { label: "X with damping", gates: "x q[0];", damping: 0.3 }] },
];
export const lessonQasm = (lesson: Lesson, variant: LessonVariant) => `OPENQASM 3.0; include "stdgates.inc"; qubit[${lesson.n}] q; bit[${lesson.n}] c; ${variant.gates}`;
